/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\learning\\MyBlogs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-f4894c18",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f4894c18").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-d29e8976",
    path: "/develop/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d29e8976").then(next)
    },
  },
  {
    path: "/develop/index.html",
    redirect: "/develop/"
  },
  {
    name: "v-ad671818",
    path: "/develop/commit.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ad671818").then(next)
    },
  },
  {
    name: "v-4282a03a",
    path: "/develop/tools.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4282a03a").then(next)
    },
  },
  {
    name: "v-46a27eda",
    path: "/learnNote/css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46a27eda").then(next)
    },
  },
  {
    name: "v-e917d75a",
    path: "/learnNote/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e917d75a").then(next)
    },
  },
  {
    path: "/learnNote/index.html",
    redirect: "/learnNote/"
  },
  {
    name: "v-26bda33c",
    path: "/learnNote/flex.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26bda33c").then(next)
    },
  },
  {
    name: "v-063ecd10",
    path: "/learnNote/sass.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-063ecd10").then(next)
    },
  },
  {
    name: "v-b459cad2",
    path: "/mobile/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b459cad2").then(next)
    },
  },
  {
    path: "/mobile/index.html",
    redirect: "/mobile/"
  },
  {
    name: "v-9d3350ee",
    path: "/tools/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9d3350ee").then(next)
    },
  },
  {
    path: "/tools/index.html",
    redirect: "/tools/"
  },
  {
    name: "v-25a83fba",
    path: "/learnNote/wechart.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25a83fba").then(next)
    },
  },
  {
    name: "v-416b544c",
    path: "/tools/git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-416b544c").then(next)
    },
  },
  {
    name: "v-14d584e2",
    path: "/tools/nvmWindows.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14d584e2").then(next)
    },
  },
  {
    name: "v-289d0d8c",
    path: "/tools/svn.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-289d0d8c").then(next)
    },
  },
  {
    name: "v-0b166b5d",
    path: "/utils/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0b166b5d").then(next)
    },
  },
  {
    path: "/utils/index.html",
    redirect: "/utils/"
  },
  {
    name: "v-6a10c80c",
    path: "/utils/html2canvas.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a10c80c").then(next)
    },
  },
  {
    name: "v-41eebc62",
    path: "/utils/exportAjax.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41eebc62").then(next)
    },
  },
  {
    name: "v-7787c390",
    path: "/vueNote/Access.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7787c390").then(next)
    },
  },
  {
    name: "v-1e089b62",
    path: "/vueNote/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e089b62").then(next)
    },
  },
  {
    path: "/vueNote/index.html",
    redirect: "/vueNote/"
  },
  {
    name: "v-ea4803cc",
    path: "/vueNote/SEO.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ea4803cc").then(next)
    },
  },
  {
    name: "v-6f3e1eba",
    path: "/vueNote/ssr.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f3e1eba").then(next)
    },
  },
  {
    name: "v-2ae25217",
    path: "/wechat/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ae25217").then(next)
    },
  },
  {
    path: "/wechat/index.html",
    redirect: "/wechat/"
  },
  {
    name: "v-52944ecc",
    path: "/vueNote/laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52944ecc").then(next)
    },
  },
  {
    name: "v-59099e14",
    path: "/wechat/html2canvas.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59099e14").then(next)
    },
  },
  {
    name: "v-4cadc954",
    path: "/wechat/share.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4cadc954").then(next)
    },
  },
  {
    name: "v-d67be560",
    path: "/develop/js.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d67be560").then(next)
    },
  },
  {
    name: "v-1e6ecf98",
    path: "/wechat/slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e6ecf98").then(next)
    },
  },
  {
    name: "v-76022498",
    path: "/wechat/taro.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76022498").then(next)
    },
  },
  {
    name: "v-60ffb030",
    path: "/wechat/dev.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60ffb030").then(next)
    },
  },
  {
    name: "v-b35d8d0c",
    path: "/develop/css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b35d8d0c").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]