/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\learning\\MyNotes\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-00538b78",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00538b78").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-7420fb95",
    path: "/develop/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7420fb95").then(next)
    },
  },
  {
    path: "/develop/index.html",
    redirect: "/develop/"
  },
  {
    name: "v-52903cb8",
    path: "/develop/commit.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52903cb8").then(next)
    },
  },
  {
    name: "v-364db9ea",
    path: "/develop/tools.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-364db9ea").then(next)
    },
  },
  {
    name: "v-3a6d988a",
    path: "/learnNote/css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a6d988a").then(next)
    },
  },
  {
    name: "v-1a0c9c12",
    path: "/learnNote/flex.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a0c9c12").then(next)
    },
  },
  {
    name: "v-89a8a6ba",
    path: "/learnNote/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-89a8a6ba").then(next)
    },
  },
  {
    path: "/learnNote/index.html",
    redirect: "/learnNote/"
  },
  {
    name: "v-4d2409ea",
    path: "/learnNote/phone.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d2409ea").then(next)
    },
  },
  {
    name: "v-8752ad2c",
    path: "/learnNote/wechart.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8752ad2c").then(next)
    },
  },
  {
    name: "v-09168e72",
    path: "/others/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09168e72").then(next)
    },
  },
  {
    path: "/others/index.html",
    redirect: "/others/"
  },
  {
    name: "v-2a4c0728",
    path: "/learnNote/sass.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a4c0728").then(next)
    },
  },
  {
    name: "v-f8dc2b1c",
    path: "/others/svn.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f8dc2b1c").then(next)
    },
  },
  {
    name: "v-1ce0ba38",
    path: "/others/webApp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ce0ba38").then(next)
    },
  },
  {
    name: "v-03233fd9",
    path: "/tools/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03233fd9").then(next)
    },
  },
  {
    path: "/tools/index.html",
    redirect: "/tools/"
  },
  {
    name: "v-a03bc0ec",
    path: "/tools/git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a03bc0ec").then(next)
    },
  },
  {
    name: "v-c31acadc",
    path: "/tools/nvmWindows.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c31acadc").then(next)
    },
  },
  {
    name: "v-5cd353ad",
    path: "/utils/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5cd353ad").then(next)
    },
  },
  {
    path: "/utils/index.html",
    redirect: "/utils/"
  },
  {
    name: "v-68e85bdc",
    path: "/utils/exportAjax.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68e85bdc").then(next)
    },
  },
  {
    name: "v-61a605aa",
    path: "/utils/html2canvas.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61a605aa").then(next)
    },
  },
  {
    name: "v-b6199d80",
    path: "/vueNote/Access.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b6199d80").then(next)
    },
  },
  {
    name: "v-63281ac2",
    path: "/vueNote/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63281ac2").then(next)
    },
  },
  {
    path: "/vueNote/index.html",
    redirect: "/vueNote/"
  },
  {
    name: "v-52176fca",
    path: "/vueNote/SEO.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52176fca").then(next)
    },
  },
  {
    name: "v-56fc9a4a",
    path: "/vueNote/laravel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56fc9a4a").then(next)
    },
  },
  {
    name: "v-01066667",
    path: "/wechat/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01066667").then(next)
    },
  },
  {
    path: "/wechat/index.html",
    redirect: "/wechat/"
  },
  {
    name: "v-3679906a",
    path: "/vueNote/ssr.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3679906a").then(next)
    },
  },
  {
    name: "v-32d38f04",
    path: "/wechat/share.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32d38f04").then(next)
    },
  },
  {
    name: "v-8ff7ec38",
    path: "/wechat/slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8ff7ec38").then(next)
    },
  },
  {
    name: "v-c2e3aa00",
    path: "/develop/js.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c2e3aa00").then(next)
    },
  },
  {
    name: "v-4d6774d0",
    path: "/wechat/dev.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d6774d0").then(next)
    },
  },
  {
    name: "v-e78b4138",
    path: "/wechat/taro.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e78b4138").then(next)
    },
  },
  {
    name: "v-6d8cab2a",
    path: "/develop/css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d8cab2a").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]