/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Blogs",
  "description": "Welcome to my blogs",
  "base": "/MyBlogs/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/animate/animate.html",
      "relativePath": "animate/animate.md",
      "key": "v-36eed43a",
      "path": "/animate/animate.html"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "开始学习 →",
        "actionLink": "/learning/",
        "footer": "Good good study ， Day day up"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-f4894c18",
      "path": "/"
    },
    {
      "title": "动画库",
      "frontmatter": {},
      "regularPath": "/animate/",
      "relativePath": "animate/README.md",
      "key": "v-636a2786",
      "path": "/animate/",
      "headers": [
        {
          "level": 2,
          "title": "Anime.js：",
          "slug": "anime-js："
        },
        {
          "level": 2,
          "title": "wow.js:",
          "slug": "wow-js"
        },
        {
          "level": 2,
          "title": "scrollReveal.js：",
          "slug": "scrollreveal-js："
        },
        {
          "level": 2,
          "title": "Waves",
          "slug": "waves"
        }
      ]
    },
    {
      "title": "CSS动画库",
      "frontmatter": {},
      "regularPath": "/animate/css.html",
      "relativePath": "animate/css.md",
      "key": "v-5455c1fa",
      "path": "/animate/css.html",
      "headers": [
        {
          "level": 2,
          "title": "Animate.css",
          "slug": "animate-css"
        },
        {
          "level": 2,
          "title": "Hover.css",
          "slug": "hover-css"
        }
      ]
    },
    {
      "title": "jQuery插件",
      "frontmatter": {},
      "regularPath": "/animate/js.html",
      "relativePath": "animate/js.md",
      "key": "v-6f149150",
      "path": "/animate/js.html",
      "headers": [
        {
          "level": 2,
          "title": "jQuery插件",
          "slug": "jquery插件"
        },
        {
          "level": 3,
          "title": "animatescroll：",
          "slug": "animatescroll："
        },
        {
          "level": 3,
          "title": "crossfade.js",
          "slug": "crossfade-js"
        },
        {
          "level": 3,
          "title": "Scrollbox",
          "slug": "scrollbox"
        },
        {
          "level": 3,
          "title": "liMarquee",
          "slug": "limarquee"
        }
      ]
    },
    {
      "title": "1. ESLint",
      "frontmatter": {},
      "regularPath": "/develop/tools.html",
      "relativePath": "develop/tools.md",
      "key": "v-4282a03a",
      "path": "/develop/tools.html",
      "headers": [
        {
          "level": 2,
          "title": "1. ESLint",
          "slug": "_1-eslint"
        },
        {
          "level": 2,
          "title": "2. Stylelint",
          "slug": "_2-stylelint"
        },
        {
          "level": 2,
          "title": "3. Prettier",
          "slug": "_3-prettier"
        },
        {
          "level": 2,
          "title": "4. husky",
          "slug": "_4-husky"
        }
      ]
    },
    {
      "title": ".eslintrc.js",
      "frontmatter": {},
      "regularPath": "/develop/commit.html",
      "relativePath": "develop/commit.md",
      "key": "v-ad671818",
      "path": "/develop/commit.html",
      "headers": [
        {
          "level": 2,
          "title": ".eslintrc.js",
          "slug": "eslintrc-js"
        },
        {
          "level": 2,
          "title": ".stylelintrc",
          "slug": "stylelintrc"
        },
        {
          "level": 2,
          "title": ".prettierrc.js",
          "slug": "prettierrc-js"
        },
        {
          "level": 2,
          "title": "package.json",
          "slug": "package-json"
        }
      ]
    },
    {
      "title": "CSS",
      "frontmatter": {},
      "regularPath": "/learnNote/css.html",
      "relativePath": "learnNote/css.md",
      "key": "v-46a27eda",
      "path": "/learnNote/css.html",
      "headers": [
        {
          "level": 2,
          "title": "CSS",
          "slug": "css"
        }
      ]
    },
    {
      "title": "网站收藏",
      "frontmatter": {},
      "regularPath": "/learnNote/",
      "relativePath": "learnNote/README.md",
      "key": "v-e917d75a",
      "path": "/learnNote/",
      "headers": [
        {
          "level": 2,
          "title": "网站收藏",
          "slug": "网站收藏"
        },
        {
          "level": 2,
          "title": "H5",
          "slug": "h5"
        },
        {
          "level": 2,
          "title": "组件",
          "slug": "组件"
        }
      ]
    },
    {
      "title": "5 种常见 flex 布局",
      "frontmatter": {},
      "regularPath": "/learnNote/flex.html",
      "relativePath": "learnNote/flex.md",
      "key": "v-26bda33c",
      "path": "/learnNote/flex.html",
      "headers": [
        {
          "level": 2,
          "title": "5 种常见 flex 布局",
          "slug": "_5-种常见-flex-布局"
        }
      ]
    },
    {
      "title": "基础",
      "frontmatter": {},
      "regularPath": "/mobile/",
      "relativePath": "mobile/README.md",
      "key": "v-b459cad2",
      "path": "/mobile/",
      "headers": [
        {
          "level": 2,
          "title": "FontSize",
          "slug": "fontsize"
        },
        {
          "level": 2,
          "title": "适配",
          "slug": "适配"
        },
        {
          "level": 2,
          "title": "手机端常见问题解决",
          "slug": "手机端常见问题解决"
        },
        {
          "level": 2,
          "title": "调试工具",
          "slug": "调试工具"
        }
      ]
    },
    {
      "title": "SASS语法",
      "frontmatter": {},
      "regularPath": "/learnNote/sass.html",
      "relativePath": "learnNote/sass.md",
      "key": "v-063ecd10",
      "path": "/learnNote/sass.html",
      "headers": [
        {
          "level": 2,
          "title": "SASS语法",
          "slug": "sass语法"
        }
      ]
    },
    {
      "title": "开发文档合集",
      "frontmatter": {},
      "regularPath": "/learnNote/wechart.html",
      "relativePath": "learnNote/wechart.md",
      "key": "v-25a83fba",
      "path": "/learnNote/wechart.html",
      "headers": [
        {
          "level": 2,
          "title": "开发文档合集",
          "slug": "开发文档合集"
        }
      ]
    },
    {
      "title": "菜鸟入门",
      "frontmatter": {},
      "regularPath": "/tools/git.html",
      "relativePath": "tools/git.md",
      "key": "v-416b544c",
      "path": "/tools/git.html",
      "headers": [
        {
          "level": 2,
          "title": "菜鸟入门",
          "slug": "菜鸟入门"
        },
        {
          "level": 2,
          "title": "命令总结",
          "slug": "命令总结"
        },
        {
          "level": 2,
          "title": "修改密码",
          "slug": "修改密码"
        },
        {
          "level": 2,
          "title": "windows下SSL证书问题",
          "slug": "windows下ssl证书问题"
        }
      ]
    },
    {
      "title": "Git分支命名",
      "frontmatter": {},
      "regularPath": "/develop/",
      "relativePath": "develop/README.md",
      "key": "v-d29e8976",
      "path": "/develop/",
      "headers": [
        {
          "level": 2,
          "title": "Git分支命名",
          "slug": "git分支命名"
        },
        {
          "level": 2,
          "title": "Commit格式",
          "slug": "commit格式"
        }
      ]
    },
    {
      "title": "svn",
      "frontmatter": {},
      "regularPath": "/tools/svn.html",
      "relativePath": "tools/svn.md",
      "key": "v-289d0d8c",
      "path": "/tools/svn.html",
      "headers": [
        {
          "level": 3,
          "title": "svn",
          "slug": "svn"
        }
      ]
    },
    {
      "title": "nvm-Windows",
      "frontmatter": {},
      "regularPath": "/tools/nvmWindows.html",
      "relativePath": "tools/nvmWindows.md",
      "key": "v-14d584e2",
      "path": "/tools/nvmWindows.html",
      "headers": [
        {
          "level": 2,
          "title": "step1：卸载原先安装的nodejs",
          "slug": "step1：卸载原先安装的nodejs"
        },
        {
          "level": 2,
          "title": "step2：下载安装",
          "slug": "step2：下载安装"
        },
        {
          "level": 2,
          "title": "step3：检查环境变量",
          "slug": "step3：检查环境变量"
        },
        {
          "level": 2,
          "title": "step4：nvm下载并使用node",
          "slug": "step4：nvm下载并使用node"
        },
        {
          "level": 3,
          "title": "为什么要删除 C:\\Program Files\\nodejs ？？？",
          "slug": "为什么要删除-c-program-files-nodejs-？？？"
        },
        {
          "level": 2,
          "title": "踩坑预警",
          "slug": "踩坑预警"
        },
        {
          "level": 3,
          "title": "Node 下载成功，npm 包下载不成功 ？？？",
          "slug": "node-下载成功，npm-包下载不成功-？？？"
        }
      ]
    },
    {
      "title": "文件下载",
      "frontmatter": {},
      "regularPath": "/utils/exportAjax.html",
      "relativePath": "utils/exportAjax.md",
      "key": "v-41eebc62",
      "path": "/utils/exportAjax.html",
      "headers": [
        {
          "level": 2,
          "title": "文件下载",
          "slug": "文件下载"
        },
        {
          "level": 2,
          "title": "获取url中的参数",
          "slug": "获取url中的参数"
        },
        {
          "level": 2,
          "title": "复制文字",
          "slug": "复制文字"
        }
      ]
    },
    {
      "title": "手机号码",
      "frontmatter": {},
      "regularPath": "/utils/",
      "relativePath": "utils/README.md",
      "key": "v-0b166b5d",
      "path": "/utils/",
      "headers": [
        {
          "level": 2,
          "title": "手机号码",
          "slug": "手机号码"
        },
        {
          "level": 2,
          "title": "email 地址",
          "slug": "email-地址"
        },
        {
          "level": 2,
          "title": "数值范围",
          "slug": "数值范围"
        },
        {
          "level": 2,
          "title": "为空",
          "slug": "为空"
        },
        {
          "level": 2,
          "title": "纯英文",
          "slug": "纯英文"
        },
        {
          "level": 2,
          "title": "纯中文",
          "slug": "纯中文"
        },
        {
          "level": 2,
          "title": "金钱数字",
          "slug": "金钱数字"
        },
        {
          "level": 2,
          "title": "字母数字",
          "slug": "字母数字"
        },
        {
          "level": 2,
          "title": "纯数字",
          "slug": "纯数字"
        },
        {
          "level": 2,
          "title": "ip 地址",
          "slug": "ip-地址"
        },
        {
          "level": 2,
          "title": "合法 url",
          "slug": "合法-url"
        },
        {
          "level": 2,
          "title": "合法身份证",
          "slug": "合法身份证"
        }
      ]
    },
    {
      "title": "使用",
      "frontmatter": {},
      "regularPath": "/utils/html2canvas.html",
      "relativePath": "utils/html2canvas.md",
      "key": "v-6a10c80c",
      "path": "/utils/html2canvas.html",
      "headers": [
        {
          "level": 2,
          "title": "使用",
          "slug": "使用"
        },
        {
          "level": 2,
          "title": "参考文章",
          "slug": "参考文章"
        }
      ]
    },
    {
      "title": "vue用户权限控制",
      "frontmatter": {},
      "regularPath": "/vueNote/Access.html",
      "relativePath": "vueNote/Access.md",
      "key": "v-7787c390",
      "path": "/vueNote/Access.html",
      "headers": [
        {
          "level": 2,
          "title": "vue用户权限控制",
          "slug": "vue用户权限控制"
        },
        {
          "level": 3,
          "title": "学习项目",
          "slug": "学习项目"
        }
      ]
    },
    {
      "title": "相关网站",
      "frontmatter": {},
      "regularPath": "/vueNote/",
      "relativePath": "vueNote/README.md",
      "key": "v-1e089b62",
      "path": "/vueNote/",
      "headers": [
        {
          "level": 3,
          "title": "相关网站",
          "slug": "相关网站"
        },
        {
          "level": 3,
          "title": "学习项目",
          "slug": "学习项目"
        }
      ]
    },
    {
      "title": "打包优化",
      "frontmatter": {},
      "regularPath": "/vueNote/SEO.html",
      "relativePath": "vueNote/SEO.md",
      "key": "v-ea4803cc",
      "path": "/vueNote/SEO.html",
      "headers": [
        {
          "level": 2,
          "title": "打包优化",
          "slug": "打包优化"
        },
        {
          "level": 2,
          "title": "调试",
          "slug": "调试"
        }
      ]
    },
    {
      "title": "转换table格式",
      "frontmatter": {},
      "regularPath": "/tools/",
      "relativePath": "tools/README.md",
      "key": "v-9d3350ee",
      "path": "/tools/",
      "headers": [
        {
          "level": 2,
          "title": "转换table格式",
          "slug": "转换table格式"
        },
        {
          "level": 2,
          "title": "富文本编辑器",
          "slug": "富文本编辑器"
        },
        {
          "level": 2,
          "title": "nrm",
          "slug": "nrm"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/vueNote/ssr.html",
      "relativePath": "vueNote/ssr.md",
      "key": "v-6f3e1eba",
      "path": "/vueNote/ssr.html"
    },
    {
      "title": "laravel 5.4使用vue",
      "frontmatter": {},
      "regularPath": "/vueNote/laravel.html",
      "relativePath": "vueNote/laravel.md",
      "key": "v-52944ecc",
      "path": "/vueNote/laravel.html",
      "headers": [
        {
          "level": 2,
          "title": "laravel 5.4使用vue",
          "slug": "laravel-5-4使用vue"
        },
        {
          "level": 2,
          "title": "学习项目",
          "slug": "学习项目"
        },
        {
          "level": 2,
          "title": "laravel-blade 语法",
          "slug": "laravel-blade-语法"
        }
      ]
    },
    {
      "title": "基础",
      "frontmatter": {},
      "regularPath": "/wechat/",
      "relativePath": "wechat/README.md",
      "key": "v-2ae25217",
      "path": "/wechat/",
      "headers": [
        {
          "level": 2,
          "title": "基础",
          "slug": "基础"
        },
        {
          "level": 2,
          "title": "零散且重要的知识点",
          "slug": "零散且重要的知识点"
        },
        {
          "level": 2,
          "title": "小程序码",
          "slug": "小程序码"
        },
        {
          "level": 2,
          "title": "打包过大",
          "slug": "打包过大"
        }
      ]
    },
    {
      "title": "Html2Canvas",
      "frontmatter": {},
      "regularPath": "/wechat/html2canvas.html",
      "relativePath": "wechat/html2canvas.md",
      "key": "v-59099e14",
      "path": "/wechat/html2canvas.html",
      "headers": [
        {
          "level": 2,
          "title": "Html2Canvas",
          "slug": "html2canvas"
        },
        {
          "level": 3,
          "title": "🌰 PC端整个页面截图",
          "slug": "pc端整个页面截图"
        },
        {
          "level": 3,
          "title": "🌰 H5页面截图",
          "slug": "h5页面截图"
        }
      ]
    },
    {
      "title": "小程序端",
      "frontmatter": {},
      "regularPath": "/wechat/share.html",
      "relativePath": "wechat/share.md",
      "key": "v-4cadc954",
      "path": "/wechat/share.html",
      "headers": [
        {
          "level": 2,
          "title": "小程序端",
          "slug": "小程序端"
        },
        {
          "level": 3,
          "title": "使用 Painter",
          "slug": "使用-painter"
        }
      ]
    },
    {
      "title": "JS 代码风格",
      "frontmatter": {},
      "regularPath": "/develop/js.html",
      "relativePath": "develop/js.md",
      "key": "v-d67be560",
      "path": "/develop/js.html",
      "headers": [
        {
          "level": 2,
          "title": "缩进",
          "slug": "缩进"
        },
        {
          "level": 2,
          "title": "空格",
          "slug": "空格"
        },
        {
          "level": 2,
          "title": "换行",
          "slug": "换行"
        },
        {
          "level": 2,
          "title": "命名",
          "slug": "命名"
        },
        {
          "level": 2,
          "title": "注释",
          "slug": "注释"
        },
        {
          "level": 2,
          "title": "变量",
          "slug": "变量"
        },
        {
          "level": 2,
          "title": "条件",
          "slug": "条件"
        },
        {
          "level": 2,
          "title": "类型转换",
          "slug": "类型转换"
        }
      ]
    },
    {
      "title": "CSS代码风格",
      "frontmatter": {},
      "regularPath": "/develop/css.html",
      "relativePath": "develop/css.md",
      "key": "v-b35d8d0c",
      "path": "/develop/css.html",
      "headers": [
        {
          "level": 2,
          "title": "缩进",
          "slug": "缩进"
        },
        {
          "level": 2,
          "title": "空格",
          "slug": "空格"
        },
        {
          "level": 2,
          "title": "选择器",
          "slug": "选择器"
        },
        {
          "level": 2,
          "title": "属性",
          "slug": "属性"
        },
        {
          "level": 2,
          "title": "属性缩写",
          "slug": "属性缩写"
        },
        {
          "level": 2,
          "title": "属性书写顺序",
          "slug": "属性书写顺序"
        },
        {
          "level": 2,
          "title": "!important",
          "slug": "important"
        },
        {
          "level": 2,
          "title": "值与单位",
          "slug": "值与单位"
        },
        {
          "level": 3,
          "title": "文本",
          "slug": "文本"
        },
        {
          "level": 3,
          "title": "数值",
          "slug": "数值"
        },
        {
          "level": 3,
          "title": "url()",
          "slug": "url"
        },
        {
          "level": 3,
          "title": "长度",
          "slug": "长度"
        },
        {
          "level": 3,
          "title": "颜色",
          "slug": "颜色"
        },
        {
          "level": 3,
          "title": "2D 位置",
          "slug": "_2d-位置"
        },
        {
          "level": 2,
          "title": "文本编排",
          "slug": "文本编排"
        },
        {
          "level": 3,
          "title": "字体族",
          "slug": "字体族"
        },
        {
          "level": 3,
          "title": "字号",
          "slug": "字号"
        },
        {
          "level": 3,
          "title": "字重",
          "slug": "字重"
        },
        {
          "level": 3,
          "title": "行高",
          "slug": "行高"
        },
        {
          "level": 2,
          "title": "响应式",
          "slug": "响应式"
        },
        {
          "level": 2,
          "title": "兼容性",
          "slug": "兼容性"
        },
        {
          "level": 3,
          "title": "属性前缀",
          "slug": "属性前缀"
        },
        {
          "level": 3,
          "title": "Hack",
          "slug": "hack"
        },
        {
          "level": 2,
          "title": "备注",
          "slug": "备注"
        },
        {
          "level": 2,
          "title": "demo",
          "slug": "demo"
        },
        {
          "level": 2,
          "title": "Less/Sass 编码规范",
          "slug": "less-sass-编码规范"
        },
        {
          "level": 3,
          "title": "代码组织",
          "slug": "代码组织"
        },
        {
          "level": 3,
          "title": "空格",
          "slug": "空格-2"
        },
        {
          "level": 3,
          "title": "运算",
          "slug": "运算"
        },
        {
          "level": 3,
          "title": "嵌套和缩进",
          "slug": "嵌套和缩进"
        },
        {
          "level": 3,
          "title": "变量",
          "slug": "变量"
        },
        {
          "level": 3,
          "title": "继承",
          "slug": "继承"
        },
        {
          "level": 3,
          "title": "混入（Mixin）",
          "slug": "混入（mixin）"
        },
        {
          "level": 3,
          "title": "注释",
          "slug": "注释"
        }
      ]
    },
    {
      "title": "插槽slot",
      "frontmatter": {},
      "regularPath": "/wechat/slot.html",
      "relativePath": "wechat/slot.md",
      "key": "v-1e6ecf98",
      "path": "/wechat/slot.html",
      "headers": [
        {
          "level": 2,
          "title": "插槽slot",
          "slug": "插槽slot"
        }
      ]
    },
    {
      "title": "插槽slot",
      "frontmatter": {},
      "regularPath": "/wechat/taro.html",
      "relativePath": "wechat/taro.md",
      "key": "v-76022498",
      "path": "/wechat/taro.html",
      "headers": [
        {
          "level": 2,
          "title": "插槽slot",
          "slug": "插槽slot"
        },
        {
          "level": 2,
          "title": "pages",
          "slug": "pages"
        },
        {
          "level": 2,
          "title": "scroll-view 标签",
          "slug": "scroll-view-标签"
        },
        {
          "level": 2,
          "title": "粘性布局 position:sticky",
          "slug": "粘性布局-position-sticky"
        },
        {
          "level": 2,
          "title": "Taro 爬坑",
          "slug": "taro-爬坑"
        },
        {
          "level": 2,
          "title": "@tarojs/cli 安装、更新失败",
          "slug": "tarojs-cli-安装、更新失败"
        },
        {
          "level": 2,
          "title": "父组件传递class给自定义子组件",
          "slug": "父组件传递class给自定义子组件"
        },
        {
          "level": 2,
          "title": "iphonex 底部小黑条",
          "slug": "iphonex-底部小黑条"
        }
      ]
    },
    {
      "title": "自定义底部导航栏",
      "frontmatter": {},
      "regularPath": "/wechat/dev.html",
      "relativePath": "wechat/dev.md",
      "key": "v-60ffb030",
      "path": "/wechat/dev.html",
      "headers": [
        {
          "level": 2,
          "title": "自定义底部导航栏",
          "slug": "自定义底部导航栏"
        },
        {
          "level": 2,
          "title": "自定义顶部导航栏",
          "slug": "自定义顶部导航栏"
        },
        {
          "level": 2,
          "title": "转发/分享",
          "slug": "转发-分享"
        },
        {
          "level": 2,
          "title": "消息订阅",
          "slug": "消息订阅"
        },
        {
          "level": 3,
          "title": "小踩坑",
          "slug": "小踩坑"
        },
        {
          "level": 2,
          "title": "消息推送",
          "slug": "消息推送"
        }
      ]
    }
  ],
  "themeConfig": {
    "displayAllHeaders": true,
    "nav": [
      {
        "text": "移动端",
        "items": [
          {
            "text": "移动端",
            "link": "/mobile/"
          },
          {
            "text": "微信小程序",
            "link": "/wechat/"
          }
        ]
      },
      {
        "text": "开发",
        "items": [
          {
            "text": "开发规范",
            "link": "/develop/"
          },
          {
            "text": "开发工具",
            "link": "/tools/"
          },
          {
            "text": "工具函数",
            "link": "/utils/"
          }
        ]
      }
    ],
    "sidebar": {
      "/develop/": [
        {
          "title": "开发规范",
          "children": [
            [
              "",
              "GIT"
            ],
            [
              "css",
              "CSS"
            ],
            [
              "js",
              "JS"
            ]
          ]
        },
        [
          "tools",
          "检查工具"
        ],
        [
          "commit",
          "检查方案"
        ]
      ],
      "/tools/": [
        [
          "",
          "在线工具"
        ],
        [
          "git",
          "Git"
        ],
        [
          "svn",
          "SVN"
        ],
        [
          "nvmWindows",
          "nvmWindows"
        ]
      ],
      "/utils/": [
        [
          "",
          "常用校验"
        ],
        [
          "exportAjax",
          "工具类"
        ],
        [
          "html2canvas",
          "html2canvas"
        ]
      ],
      "/wechat/": [
        [
          "",
          "入门须知"
        ],
        [
          "taro",
          "爬坑"
        ],
        [
          "dev",
          "常见业务场景"
        ],
        {
          "title": "页面截图",
          "collapsable": false,
          "sidebarDepth": 0,
          "children": [
            "html2canvas",
            [
              "share",
              ""
            ]
          ]
        }
      ],
      "/mobile/": [
        ""
      ]
    }
  }
}